import cors from "cors"
import express from "express"
import dotenv from "dotenv"
import cookieParser from "cookie-parser"
import path from "path"

import authRouter from "./routes/auth.route.js";
import messageRouter from "./routes/message.route.js";
import connectDB from "./lib/db.js";
import { app, server, io } from "./lib/socket.js";



dotenv.config();
const PORT = process.env.PORT || 5001;



//middleware  
app.use(cors({          // handles cors error(Cross origin resource sharing - allow backend and front end localhost URL to work together)
    origin:"http://localhost:5173",
    credentials:true
}))
app.use(express.json({limit:'10mb'})); // this middleware allows to access req.body
app.use(cookieParser()); //this middleware is used to get token from the cookie generated by authorized user (req.cookie._tokenName_(like:jwt))
const __dirname = path.resolve() //gets the path of backend -- like D:\personal projects\mern-Chat Application\backend



app.use("/api/auth", authRouter);
app.use("/api/message", messageRouter);


if(process.env.NODE_ENV==="production"){
    app.use(express.static(path.join(__dirname,"../frontend/dist"))); //middleware used to join path of backend D:/mern/backend with D:/frontend/dist

    app.get(/(.*)/, (req, res) => {   // * -> if any route other than backend we will run the frontend app'n
        res.sendFile(path.join(__dirname, "../frontend", "dist", "index.html"))
    })
}


connectDB().then(() => {
    server.listen(PORT, () => {
        console.log("server running on port : " + PORT);
    })
})





